# Generated by Django 5.0.4 on 2024-04-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors_app', '0003_vendor_data_operationmaintainanceremark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_data',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor_data',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
